# Generated by Django 5.1.7 on 2025-03-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentresponse',
            name='count',
        ),
    ]
