# Generated by Django 5.1.7 on 2025-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_commentresponse_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='negative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='positive_count',
            field=models.IntegerField(default=0),
        ),
    ]
